version: '3.4'

services:
  webapp:
    build:
      context: .
      target: dev
    ports:
      - '3010:3010'
    volumes:
      - .:/app
      - /app/node_modules
  tasks-api:
    image: vincentza/get-shit-done-backend:0.2
    ports:
      - 3005:3005
